sample_public = {
  "Accept": "*/*",
  "Accept-Encoding": "gzip, deflate, br",
  "Accept-Language": "en",
  "Content-Length": "192",
  "Content-Type": "application/json",
  "Disguised-Host": "your_app_service.azurewebsites.net",
  "Host": "your_app_service.azurewebsites.net",
  "Max-Forwards": "10",
  "Origin": "https://your_app_service.azurewebsites.net",
  "Referer": "https://your_app_service.azurewebsites.net/",
  "Sec-Ch-Ua": "\"Microsoft Edge\";v=\"113\", \"Chromium\";v=\"113\", \"Not-A.Brand\";v=\"24\"",
  "Sec-Ch-Ua-Mobile": "?0",
  "Sec-Ch-Ua-Platform": "\"Windows\"",
  "Sec-Fetch-Dest": "empty",
  "Sec-Fetch-Mode": "cors",
  "Sec-Fetch-Site": "same-origin",
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.42",
  "X-Appservice-Proto": "https",
  "X-Arr-Ssl": "2048|256|CN=Microsoft Azure TLS Issuing CA 02, O=Microsoft Corporation, C=US|CN=*.azurewebsites.net, O=Microsoft Corporation, L=Redmond, S=WA, C=US",
  "X-Forwarded-For": "22.222.222.22:64379",
  "X-Forwarded-Proto": "https",
  "X-Forwarded-Tlsversion": "1.2",
  "X-Original-Url": "/chatgpt",
  "X-Site-Deployment-Id": "your_app_service",
  "X-Waws-Unencoded-Url": "/chatgpt"
}
